package it.tecnosystemi.TS.Utils;

import it.tecnosystemi.TS.Model.ControlUnit;
import it.tecnosystemi.TS.Model.ModBusRecipe;
import it.tecnosystemi.TS.Model.Plant;
import it.tecnosystemi.TS.Model.TimeZoneServer;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Constants {
    public static final int ADDNEWCU = 17;
    public static final int ADDREGTAG = 7;
    public static int AS_MENU = 1;
    public static int AS_POPUP = 0;
    public static final String BUNDLE_LISTA = "lista";
    public static final String BUNDLE_MENU = "menu";
    public static final String BUNDLE_POSX = "xpos";
    public static final String BUNDLE_POSY = "ypos";
    public static final String BUNDLE_TITLE = "title";
    public static boolean CHECKED_TS_VER = false;
    public static final int CHECKMAIL = 1;
    public static final int CHECKNEWCU = 18;
    public static final String COMMAND10MIN = "1";
    public static final String COMMANDSENT = "0";
    public static final int COM_ERROR = 1;
    public static final int COM_PICOERROR = 2;
    public static final int CONNECTUSRTOPICO = 24;
    public static final int CONNECTUSRTOUC = 8;
    public static final int CU_OFF = 1;
    public static final int CU_ON = 0;
    public static final String[] CU_ONOFF_ICON = {"", ""};
    public static final String[] CU_OPERATINGMODE_ICON = {"", "", "", ""};
    public static final int CU_OPERATINGMODE_RAFF = 1;
    public static final int CU_OPERATINGMODE_UMD = 2;
    public static final int CU_OPERATINGMODE_VENT = 3;
    public static final int CU_RAFF = 1;
    public static final int CU_RISC = 0;
    public static final String[] CU_RUFFRISC_ICON = {"", ""};
    public static final int DELETE = 2;
    public static final int DELETEUSRFROMIMP = 25;
    public static final int DELETEUSRFROMUC = 10;
    public static final int DELUSER = 20;
    public static ControlUnit DEMO_CU = null;
    public static int DEMO_DEV_INDEX = 0;
    public static int DEMO_IMP_INDEX = 0;
    public static int DEMO_INDEX_ZONA = 0;
    public static int DEMO_PICO_INDEX = 0;
    public static int DEVICE_TYPE_6X = 3;
    public static int DEVICE_TYPE_PICO = 1;
    public static int DEVICE_TYPE_PROAIR = 0;
    public static int DEVICE_TYPE_VMC = 2;
    public static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    public static final int ERROR_PIN = 2;
    public static final String FA_INFO = "";
    public static final String FA_UPDATE = "";
    public static final String FIX_PWD = "PwdProAir";
    public static final String FIX_TOKEN = "Ga5mM61KCm5Bk18lhD5J999jC2Mu0Vaf";
    public static final String FIX_USR = "UsrProAir";
    public static final Map<Integer, Double> FROMFTOC;
    public static final String FW_DIRECTORY_NAME = "FWDir";
    public static String GDPRFROMHOME = "GDPRFROMHOME";
    public static String GDPRFROMLOGIN = "GDPRFROMLOGIN";
    public static String GDPRLOGINMODEL = "LoginModel";
    public static String GDprPWD = "GDprPWD";
    public static String GDprUSERNAME = "GDprUSERNAME";
    public static final int GET = 0;
    public static final int GETFW = 5;
    public static final int GETFWSINFO = 4;
    public static final int GETHOME = 9;
    public static final int GETHOMETS = 23;
    public static final int GETSTATE = 11;
    public static final int GETSTATEFIRST = 12;
    public static final int GETTW = 14;
    public static final int HTTP_READ_TIMEOUT = 15000;
    public static final int HTTP_READ_TIMEOUT_CONFIG = 240000;
    public static final int HTTP_REQUEST_TIMEOUT = 15000;
    public static final int ICON_CASA = 0;
    public static final int ICON_FABBRICA = 1;
    public static final int ICON_HOTEL = 3;
    public static final int ICON_NEGOZIO = 2;
    public static final String[] ICON_TYPE = {"", "", "", ""};
    public static final String INP_INDEX = "INP_INDEX";
    public static final String INTENT_BOOTLOADER = "isbootloader";
    public static final String INTENT_CU = "control_unit";
    public static final String INTENT_ICON = "icon";
    public static final String INTENT_INDEX = "index";
    public static final String INTENT_INDEXZONA = "indexzona";
    public static final String INTENT_NAME = "name";
    public static final String INTENT_NOMECU = "nome_cu";
    public static final String INTENT_PICO = "pico";
    public static final String INTENT_PIN = "pin";
    public static final String INTENT_SERIAL = "serial";
    public static final String INTENT_SETUPMODE = "setupmode";
    public static final String INTENT_SSID = "ssid";
    public static final String INTENT_UNITM = "unitm";
    public static final String INTENT_VMC = "vmc";
    public static final String INTENT_WIFI = "wifi";
    public static final String INTENT_ZONA = "zona";
    public static final int IRNO = 0;
    public static final int IRSI = 1;
    public static boolean ISDEMO = false;
    public static String JSON_COMMAND_END = "f";
    public static String JSON_COMMAND_START = "i";
    public static String JSON_COMMAND_TEMP = "t";
    public static String JSON_CU_ERR = "Errors";
    public static String JSON_CU_FEST = "FEst";
    public static String JSON_CU_FINV = "FInv";
    public static String JSON_CU_FWVER = "FWVer";
    public static String JSON_CU_H24 = "h24";
    public static String JSON_CU_ICON = "Icon";
    public static String JSON_CU_IP = "IP";
    public static String JSON_CU_IRPRESENT = "IrPresent";
    public static String JSON_CU_ISCOOLING = "IsCooling";
    public static String JSON_CU_ISOFF = "IsOFF";
    public static String JSON_CU_ISOFFLINE = "IsOffline";
    public static String JSON_CU_LASCONFIGTUPDATE = "LastConfigUpdate";
    public static String JSON_CU_LASTSYNCUPDATE = "LastSyncUpdate";
    public static String JSON_CU_NAME = "Name";
    public static String JSON_CU_NUMERR = "NumErrors";
    public static String JSON_CU_OPERMODE = "OperatingModeCooling";
    public static String JSON_CU_PIN = "Pin";
    public static String JSON_CU_PINOFF = "PinOffline";
    public static String JSON_CU_SERIAL = "Serial";
    public static String JSON_CU_SSID = "SSID";
    public static String JSON_CU_TCAN = "TempCan";
    public static String JSON_CU_UNIMESURE = "UnitOfMeasure";
    public static String JSON_CU_ZONE = "Zones";
    public static String[] JSON_GIORNI = {"Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"};
    public static String JSON_LVDV_Type = "LVDV_Type";
    public static String JSON_MAXCLEANFLASHVR = "MaxCleanFlashVr";
    public static String JSON_MEMORYSIZE = "MemorySize";
    public static String JSON_MICROTYPE = "MicroType";
    public static String JSON_MINCLEANFLASHVR = "MinCleanFlashVr";
    public static String JSON_NOCMD = "no_cmd";
    public static String JSON_OFFLINE_COMMAND_C = "c";
    public static String JSON_OFFLINE_COMMAND_CBADGE = "c_badge";
    public static String JSON_OFFLINE_COMMAND_CBADGE_R = "b";
    public static String JSON_OFFLINE_COMMAND_COOLMOD = "cool_mod";
    public static String JSON_OFFLINE_COMMAND_COOLMOD_R = "cl_m";
    public static String JSON_OFFLINE_COMMAND_CO_R = "co";
    public static String JSON_OFFLINE_COMMAND_CRONOON = "crono_on";
    public static String JSON_OFFLINE_COMMAND_CWIN = "c_win";
    public static String JSON_OFFLINE_COMMAND_CWIN_R = "w";
    public static String JSON_OFFLINE_COMMAND_ERR = "err";
    public static String JSON_OFFLINE_COMMAND_ERRCU = "err_cu";
    public static String JSON_OFFLINE_COMMAND_EV = "EV";
    public static String JSON_OFFLINE_COMMAND_EV_SET = "EV_set";
    public static String JSON_OFFLINE_COMMAND_FAN = "fan";
    public static String JSON_OFFLINE_COMMAND_FANSET = "fan_set";
    public static String JSON_OFFLINE_COMMAND_FEST = "f_est";
    public static String JSON_OFFLINE_COMMAND_FEST_R = "fe";
    public static String JSON_OFFLINE_COMMAND_FINV = "f_inv";
    public static String JSON_OFFLINE_COMMAND_FINV_R = "fi";
    public static String JSON_OFFLINE_COMMAND_IDZONA = "id_zona";
    public static String JSON_OFFLINE_COMMAND_IDZONAGETSTATE = "id_zona";
    public static String JSON_OFFLINE_COMMAND_IDZONA_R = "nr";
    public static String JSON_OFFLINE_COMMAND_IRPRESENT = "ir_present";
    public static String JSON_OFFLINE_COMMAND_IRPRESENT_R = "ir";
    public static String JSON_OFFLINE_COMMAND_ISCOOL = "is_cool";
    public static String JSON_OFFLINE_COMMAND_ISCOOL_R = "cl";
    public static String JSON_OFFLINE_COMMAND_ISCRONO = "is_crono";
    public static String JSON_OFFLINE_COMMAND_ISOFF = "is_off";
    public static String JSON_OFFLINE_COMMAND_ISOFFCU = "is_off_cu";
    public static String JSON_OFFLINE_COMMAND_ISOFF_R = "off";
    public static String JSON_OFFLINE_COMMAND_MASTERNR = "master_nr";
    public static String JSON_OFFLINE_COMMAND_MASTERNR_R = "m_nr";
    public static String JSON_OFFLINE_COMMAND_NAME = "name";
    public static String JSON_OFFLINE_COMMAND_NAME_R = "n";
    public static String JSON_OFFLINE_COMMAND_NRZONAGETSTATE = "nr";
    public static String JSON_OFFLINE_COMMAND_OFFLINE = "offline";
    public static String JSON_OFFLINE_COMMAND_PIN = "pin";
    public static String JSON_OFFLINE_COMMAND_SHU = "shu";
    public static String JSON_OFFLINE_COMMAND_SHUSET = "shu_set";
    public static String JSON_OFFLINE_COMMAND_TCAN = "t_can";
    public static String JSON_OFFLINE_COMMAND_TCAN_R = "tc";
    public static String JSON_OFFLINE_COMMAND_TEMP = "t";
    public static String JSON_OFFLINE_COMMAND_TEMPSET = "t_set";
    public static String JSON_OFFLINE_COMMAND_TEMPSET_R = "ts";
    public static String JSON_OFFLINE_COMMAND_UMD = "u";
    public static String JSON_OFFLINE_COMMAND_UMDSET = "u_set";
    public static String JSON_OFFLINE_COMMAND_UMDSET_R = "us";
    public static String JSON_OFFLINE_COMMAND_WIFIPDW = "wifi_pwd";
    public static String JSON_OFFLINE_COMMAND_WIFISEC = "wifi_sec";
    public static String JSON_OFFLINE_COMMAND_WIFISID = "wifi_ssid";
    public static String JSON_OFFLINE_COMMAND_ZONE = "zone";
    public static String JSON_POLARISTYPE = "PolarisType";
    public static String JSON_RES = "res";
    public static String JSON_SER = "ser";
    public static String JSON_VERSION = "Version";
    public static String JSON_WIFI = "aps";
    public static String JSON_WIFIVERSION = "WiFiVersion";
    public static String JSON_ZONE_ID = "ZoneId";
    public static final int LOGIN = 2;
    public static String LastAppVr = null;
    public static String LastAppVrTxt = null;
    public static String LastFWVr = null;
    public static List<ModBusRecipe> MODBUSRECEPIES = null;
    public static final int NEW_PRIVACY = 1;
    public static final String NOTIFIC_PLAT = "fcm2";
    public static final String ONLYNAME = "2";
    public static String PARAM_LDESC_STRING = "param_ldesc_";
    public static String PARAM_NAME_STRING = "param_name_";
    public static String PARAM_SDESC_STRING = "param_sdesc_";
    public static final int PICO_CHECKCONFIG = 29;
    public static final int PICO_GETFASCE = 33;
    public static final int PICO_GETSLAVE = 30;
    public static final int PICO_GETSTATO = 26;
    public static final int PICO_SETAPCONFIG = 28;
    public static final int PICO_SETFASCE = 34;
    public static final int PICO_SETSLAVE = 31;
    public static final int PICO_SETSTATO = 27;
    public static final int POPUPCNGNUM_ORARIO_12 = 2;
    public static final int POPUPCNGNUM_ORARIO_24 = 1;
    public static final int POPUPCNGNUM_TEMP = 0;
    public static final int POST = 1;
    public static final String PREF_6X_DEVS = "6XDevs";
    public static final String PREF_CONTTOKEN = "cont_token";
    public static final String PREF_DEVS_TS = "DevsTS";
    public static final String PREF_INFOFWS = "infofw";
    public static final String PREF_LAST_USER_NAME = "LASTUSERNAME";
    public static final int PREF_NO_NOTIF = 0;
    public static final String PREF_PICO_DEVS = "PICODevs";
    public static final String PREF_PWD = "pwd";
    public static final String PREF_REGID_NAME = "ANHSettings";
    public static final String PREF_REGID_SETTING_NAME = "ANHRegistrationId";
    public static final String PREF_REMEBERME = "rememberme";
    public static final int PREF_SI_NOTIF = 1;
    public static final String PREF_TOKEN = "token";
    public static final String PREF_TOKEN_DATE = "tokendate";
    public static final String PREF_TOKEN_VALUE = "TOKENVALUE";
    public static final String PREF_UC_HOME = "HomeUC";
    public static final String PREF_UC_HOME_TS = "HomeUC_TS";
    public static final String PREF_USERNAME = "username";
    public static final String PREF_USER_ID = "userid";
    public static final String PREF_VMC_DEVS = "VMCevs";
    public static final int PRIVACYSIGNUP = 0;
    public static final int PUT = 3;
    public static int RECIPE_MAX_SIZE = 10;
    public static final int RECPWD = 3;
    public static final int REGNOTIFICATIONS = 6;
    public static final int RESETCON = 19;
    public static String RESET_PIN = "ProAIR2019";
    public static final int RESTORECONFIG = 21;
    public static final int RESULT_DEVICENONVALIDO = 5;
    public static final int RESULT_ERROR = -1;
    public static final int RESULT_INCORRECTPWDUSER = 1;
    public static final int RESULT_MAILEXIST = 9;
    public static final int RESULT_MOREDEVICES = 8;
    public static final int RESULT_NEWTERMOFUSE = 10;
    public static final int RESULT_OK = 0;
    public static final int RESULT_PWDSCADUTA = 6;
    public static final int RESULT_PWDTEMPSCADUTA = 7;
    public static final int RESULT_USRBLOCCATO = 3;
    public static final int RESULT_USRDAATTIVARE = 2;
    public static final int RESULT_USRNONTROVATO = 4;
    public static final int RESULT_WIFI = 1234;
    public static String SALT = "ns91wr48";
    public static int SEI_X_TEMP_UM = 0;
    public static String SEI_X_TEMP_UM_PREF = "SEI_X_TEMP_UM_PREF";
    public static final int SETUP_ADDCUOFFLINE = 4;
    public static final int SETUP_ADDCUONLINE = 2;
    public static final int SETUP_ADDPICOSLAVE = 5;
    public static final int SETUP_CONFIGCUOFFLINE = 3;
    public static final int SETUP_CONFIGCUONLINE = 1;
    public static final int SIGNUP = 0;
    public static List<TimeZoneServer> TIMEZONES = null;
    public static final int TS_OP_ADD_DISP = 0;
    public static final int TS_OP_AGG_FW = 1;
    public static final String TS_TIPO_OP = "TS_TIPO_OP";
    public static final int UM_CELSIUS = 0;
    public static final int UM_FAHRENHEIT = 1;
    public static final String[] UM_ICON = {"", ""};
    public static final int UPDADDPLANT = 22;
    public static final int UPDCUDATETIME = 16;
    public static final int UPDSTATE = 13;
    public static final int UPDTW = 15;
    public static final int UPD_GDPR = 32;
    public static final String WIFI_NAME_6X_CONFIG = "P6X_config";
    public static final String WIFI_NAME_BOOT = "POLARIS_UPDATE";
    public static final String WIFI_NAME_CONFIG = "POLARIS_CONFIG";
    public static final String WIFI_NAME_OFFLINE = "POLARIS_";
    public static final String WIFI_NAME_OFFLINE_6X = "P6X_";
    public static final String WIFI_NAME_OFFLINE_PICO = "Pico_";
    public static final String WIFI_NAME_OFFLINE_VMC = "VMC_";
    public static final String WIFI_NAME_PICO_CONFIG = "Pico_config";
    public static final String WIFI_NAME_VMC_CONFIG = "VMC_config";
    public static final String WIFI_PWD_6X_CONFIG = "12345678";
    public static final String WIFI_PWD_BOOT = "TS123456";
    public static final String WIFI_PWD_CONFIG = "PWD_CONFIG";
    public static final String WIFI_PWD_OFFLINE = "TS_";
    public static final String WIFI_PWD_OFFLINE_6X = "TS_";
    public static final String WIFI_PWD_OFFLINE_PICO = "TS_";
    public static final String WIFI_PWD_OFFLINE_VMC = "VMC_";
    public static final String WIFI_PWD_PICO_CONFIG = "12345678";
    public static final String WIFI_PWD_VMC_CONFIG = "12345678";
    public static final int ZONE_CRONO = 1;
    public static final int ZONE_EV_NO = -1;
    public static final int ZONE_EV_OFF = 0;
    public static final int ZONE_EV_ON = 1;
    public static final int ZONE_FANCOIL_A1 = 1;
    public static final int ZONE_FANCOIL_A2 = 2;
    public static final int ZONE_FANCOIL_A3 = 3;
    public static final int ZONE_FANCOIL_AUTO = 7;
    public static final int ZONE_FANCOIL_AUTO1 = 4;
    public static final int ZONE_FANCOIL_AUTO2 = 5;
    public static final int ZONE_FANCOIL_AUTO3 = 6;
    public static final int ZONE_FANCOIL_CHIUSA = 0;
    public static final String[] ZONE_FANCOIL_ICON = {"", "", "", "", "", "", "", ""};
    public static final int ZONE_FANCOIL_NO = -1;
    public static final int ZONE_MAN = 0;
    public static final String[] ZONE_MANCRONO_ICON = {"", ""};
    public static final int ZONE_SERRANDA_A1 = 1;
    public static final int ZONE_SERRANDA_A2 = 2;
    public static final int ZONE_SERRANDA_A3 = 3;
    public static final int ZONE_SERRANDA_AUTO = 7;
    public static final int ZONE_SERRANDA_AUTO1 = 4;
    public static final int ZONE_SERRANDA_AUTO2 = 5;
    public static final int ZONE_SERRANDA_AUTO3 = 6;
    public static final int ZONE_SERRANDA_CHIUSA = 0;
    public static final String[] ZONE_SERRANDA_ICON = {"", "", "", "", "", "", "", ""};
    public static final int ZONE_SERRANDA_NO = -1;
    public static boolean _LOG = true;
    public static String android_id = null;
    public static String ip = "10.0.0.1";
    public static List<Plant> listaImpianti = null;
    public static boolean modesviluppatore = false;
    public static boolean modesviluppatoreBootloader = false;
    public static int port = 1235;
    public static int tempmaxC = 35;
    public static int tempmaxF = 95;
    public static int tempmaxFCan = 86;
    public static int tempminC = 10;
    public static int tempminF = 50;
    public static int tempminFCan = 64;
    public static String token = "";
    public static String user = "";
    public static int userId;

    public static class PICO_JSON {
        public static final String MQTT_ST = "mqtt_sta";
        public static final String PICO_ST = "pico_st";
        public static final String SERIAL = "ser";
        public static final String WIFI_ST = "wifi_sta";
    }

    public static class SeiX_STA {
        public static final String MQTT_ST = "mqtt_sta";
        public static final String NET_ST = "net_st";
        public static final String SERIAL = "ser";
        public static final String WIFI_ST = "wifi_sta";
    }

    public static class VMC_STA {
        public static final String MQTT_ST = "mqtt_sta";
        public static final String NET_ST = "net_st";
        public static final String SERIAL = "ser";
        public static final String WIFI_ST = "wifi_sta";
    }

    static {
        HashMap hashMap = new HashMap();
        hashMap.put(50, Double.valueOf(10.2d));
        hashMap.put(51, Double.valueOf(10.8d));
        hashMap.put(52, Double.valueOf(11.4d));
        hashMap.put(53, Double.valueOf(11.9d));
        hashMap.put(54, Double.valueOf(12.5d));
        hashMap.put(55, Double.valueOf(13.0d));
        hashMap.put(56, Double.valueOf(13.6d));
        hashMap.put(57, Double.valueOf(14.1d));
        hashMap.put(58, Double.valueOf(14.7d));
        hashMap.put(59, Double.valueOf(15.2d));
        hashMap.put(60, Double.valueOf(15.8d));
        hashMap.put(61, Double.valueOf(16.4d));
        hashMap.put(62, Double.valueOf(16.9d));
        hashMap.put(63, Double.valueOf(17.4d));
        hashMap.put(64, Double.valueOf(18.0d));
        hashMap.put(65, Double.valueOf(18.6d));
        hashMap.put(66, Double.valueOf(19.1d));
        hashMap.put(67, Double.valueOf(19.7d));
        hashMap.put(68, Double.valueOf(20.2d));
        hashMap.put(69, Double.valueOf(20.8d));
        hashMap.put(70, Double.valueOf(21.3d));
        hashMap.put(71, Double.valueOf(21.9d));
        hashMap.put(72, Double.valueOf(22.4d));
        hashMap.put(73, Double.valueOf(23.0d));
        hashMap.put(74, Double.valueOf(23.6d));
        hashMap.put(75, Double.valueOf(24.1d));
        hashMap.put(76, Double.valueOf(24.7d));
        hashMap.put(77, Double.valueOf(25.2d));
        hashMap.put(78, Double.valueOf(25.8d));
        hashMap.put(79, Double.valueOf(26.3d));
        hashMap.put(80, Double.valueOf(26.9d));
        hashMap.put(81, Double.valueOf(27.4d));
        hashMap.put(82, Double.valueOf(28.0d));
        hashMap.put(83, Double.valueOf(28.6d));
        hashMap.put(84, Double.valueOf(29.1d));
        hashMap.put(85, Double.valueOf(29.7d));
        hashMap.put(86, Double.valueOf(30.2d));
        hashMap.put(87, Double.valueOf(30.8d));
        hashMap.put(88, Double.valueOf(31.3d));
        hashMap.put(89, Double.valueOf(31.9d));
        hashMap.put(90, Double.valueOf(32.4d));
        hashMap.put(91, Double.valueOf(33.0d));
        hashMap.put(92, Double.valueOf(33.6d));
        hashMap.put(93, Double.valueOf(34.1d));
        hashMap.put(94, Double.valueOf(34.7d));
        hashMap.put(95, Double.valueOf(35.0d));
        FROMFTOC = Collections.unmodifiableMap(hashMap);
    }
}
