package it.tecnosystemi.TS.Utils;

import android.content.Context;
import it.tecnosystemi.TS.Model.ControlUnit;
import it.tecnosystemi.TS.Model.Crono;
import it.tecnosystemi.TS.Model.Device;
import it.tecnosystemi.TS.Model.Pico;
import it.tecnosystemi.TS.Model.Plant;
import it.tecnosystemi.TS.Model.Zona;
import it.tecnosystemi.TS.R;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class DataClass {
    public static DataClass istance;
    public static Context mcontext;
    public ArrayList<ControlUnit> controlunit_list;
    public ArrayList<byte[]> firmware_chunk_list;
    public ArrayList<Pico> pico_list;

    public static DataClass getInstance(Context context) {
        if (istance == null) {
            DataClass dataClass = new DataClass();
            istance = dataClass;
            dataClass.firmware_chunk_list = new ArrayList<>();
            istance.controlunit_list = new ArrayList<>();
            istance.pico_list = new ArrayList<>();
            mcontext = context;
        }
        return istance;
    }

    public void populateDemo(Context context) {
        this.controlunit_list.clear();
        Constants.listaImpianti = new ArrayList();
        this.pico_list.clear();
        ControlUnit controlUnit = new ControlUnit(context.getResources().getString(R.string.demo_controlunit1));
        controlUnit.setSerial("414212345678");
        controlUnit.setIcontype(0);
        controlUnit.setUnitOfMesure(0);
        controlUnit.setIsOff(false);
        controlUnit.setOperatingMode(2);
        controlUnit.setIsCooling(true);
        controlUnit.setIr_present(0);
        controlUnit.setT_can(23);
        Device device = new Device();
        device.setLVDV_Type(Constants.DEVICE_TYPE_PROAIR);
        device.setSerial(controlUnit.getSerial());
        device.setName(controlUnit.getName());
        Plant plant = new Plant();
        plant.setLVPL_Icon(controlUnit.getIcontype());
        plant.setLVPL_Name(controlUnit.getName());
        plant.setListDevices(new ArrayList());
        plant.setLVPL_Id(1);
        plant.getListDevices().add(device);
        Constants.listaImpianti.add(plant);
        ArrayList arrayList = new ArrayList();
        ArrayList arrayList2 = new ArrayList();
        Crono crono = new Crono();
        Crono crono2 = new Crono();
        Crono crono3 = new Crono();
        Crono crono4 = new Crono();
        crono.setStartTime("09:00");
        crono2.setStartTime("10:00");
        crono3.setStartTime("18:00");
        crono4.setStartTime("18:00");
        crono.setEndTime("10:00");
        crono2.setEndTime("12:00");
        crono3.setEndTime("21:00");
        crono4.setEndTime("19:00");
        crono.setTemperatura("21");
        crono2.setTemperatura("21");
        crono3.setTemperatura("20");
        crono4.setTemperatura("21");
        arrayList2.add(crono2.copyforDemo());
        arrayList2.add(crono3.copyforDemo());
        arrayList2.add((Object) null);
        arrayList2.add((Object) null);
        arrayList.add(arrayList2);
        ArrayList arrayList3 = new ArrayList();
        arrayList3.add(crono3.copyforDemo());
        arrayList3.add((Object) null);
        arrayList3.add((Object) null);
        arrayList3.add((Object) null);
        arrayList.add(arrayList3);
        ArrayList arrayList4 = new ArrayList();
        arrayList4.add(crono2.copyforDemo());
        arrayList4.add(crono3.copyforDemo());
        arrayList4.add((Object) null);
        arrayList4.add((Object) null);
        arrayList.add(arrayList4);
        ArrayList arrayList5 = new ArrayList();
        arrayList5.add(crono3.copyforDemo());
        arrayList5.add((Object) null);
        arrayList5.add((Object) null);
        arrayList5.add((Object) null);
        arrayList.add(arrayList5);
        ArrayList arrayList6 = new ArrayList();
        arrayList6.add(crono2.copyforDemo());
        arrayList6.add(crono3.copyforDemo());
        arrayList6.add((Object) null);
        arrayList6.add((Object) null);
        arrayList.add(arrayList6);
        ArrayList arrayList7 = new ArrayList();
        arrayList7.add(crono.copyforDemo());
        arrayList7.add(crono2.copyforDemo());
        arrayList7.add(crono3.copyforDemo());
        arrayList7.add((Object) null);
        arrayList7.add((Object) null);
        arrayList.add(arrayList7);
        ArrayList arrayList8 = new ArrayList();
        arrayList8.add(crono.copyforDemo());
        arrayList8.add(crono4.copyforDemo());
        arrayList8.add((Object) null);
        arrayList8.add((Object) null);
        arrayList8.add((Object) null);
        arrayList.add(arrayList8);
        ArrayList arrayList9 = new ArrayList();
        Zona zona = new Zona();
        zona.setName(context.getResources().getString(R.string.demo_cu1_zone1));
        zona.setOff(false);
        zona.setManCrono(0);
        zona.setTemp("20.5");
        zona.setSetTemp("21");
        zona.setSerrandaSet(1);
        zona.setSerranda(1);
        zona.setEV(-1);
        zona.setFancoilSet(-1);
        zona.setFancoil(-1);
        zona.setZoneId(1);
        zona.setCrono(arrayList);
        zona.setSetUmd("500");
        zona.setUmd("560");
        arrayList9.add(zona);
        Zona zona2 = new Zona();
        zona2.setName(context.getResources().getString(R.string.demo_cu1_zone2));
        zona2.setOff(false);
        zona2.setManCrono(1);
        zona2.setTemp("20.0");
        zona2.setSetTemp("21");
        zona2.setSerrandaSet(2);
        zona2.setSerranda(2);
        zona2.setEV(-1);
        zona2.setFancoilSet(-1);
        zona2.setFancoil(-1);
        zona2.setZoneId(2);
        zona2.setCrono(arrayList);
        zona2.setSetUmd("560");
        zona2.setUmd("560");
        arrayList9.add(zona2);
        Zona zona3 = new Zona();
        zona3.setName(context.getResources().getString(R.string.demo_cu1_zone3));
        zona3.setOff(false);
        zona3.setManCrono(0);
        zona3.setTemp("21.5");
        zona3.setSetTemp("21");
        zona3.setSerrandaSet(7);
        zona3.setSerranda(0);
        zona3.setEV(-1);
        zona3.setFancoilSet(-1);
        zona3.setFancoil(-1);
        zona3.setZoneId(3);
        zona3.setCrono(arrayList);
        zona3.setSetUmd("560");
        zona3.setUmd("560");
        arrayList9.add(zona3);
        Zona zona4 = new Zona();
        zona4.setName(context.getResources().getString(R.string.demo_cu1_zone4));
        zona4.setOff(true);
        zona4.setManCrono(1);
        zona4.setTemp("20.0");
        zona4.setSetTemp("22");
        zona4.setSerrandaSet(-1);
        zona4.setSerranda(-1);
        zona4.setEV(0);
        zona4.setFancoilSet(-1);
        zona4.setFancoil(-1);
        zona4.setZoneId(4);
        zona4.setCrono(arrayList);
        zona4.setSetUmd("560");
        zona4.setUmd("560");
        arrayList9.add(zona4);
        Zona zona5 = new Zona();
        zona5.setName(context.getResources().getString(R.string.demo_cu1_zone5));
        zona5.setOff(false);
        zona5.setManCrono(0);
        zona5.setTemp("17.5");
        zona5.setSetTemp("17");
        zona5.setSerrandaSet(7);
        zona5.setSerranda(0);
        zona5.setEV(1);
        zona5.setFancoilSet(-1);
        zona5.setFancoil(-1);
        zona5.setZoneId(5);
        zona5.setCrono(arrayList);
        zona5.setSetUmd("560");
        zona5.setUmd("560");
        arrayList9.add(zona5);
        Zona zona6 = new Zona();
        zona6.setName(context.getResources().getString(R.string.demo_cu1_zone7));
        zona6.setOff(false);
        zona6.setManCrono(0);
        zona6.setTemp("17.0");
        zona6.setSetTemp("18");
        zona6.setSerrandaSet(1);
        zona6.setSerranda(1);
        zona6.setEV(1);
        zona6.setFancoilSet(-1);
        zona6.setFancoil(-1);
        zona6.setZoneId(6);
        zona6.setCrono(arrayList);
        zona6.setSetUmd("560");
        zona6.setUmd("560");
        arrayList9.add(zona6);
        Zona zona7 = new Zona();
        zona7.setName(context.getResources().getString(R.string.demo_cu1_zone6));
        zona7.setOff(false);
        zona7.setManCrono(1);
        zona7.setTemp("17.0");
        zona7.setSetTemp("18");
        zona7.setSerrandaSet(1);
        zona7.setSerranda(1);
        zona7.setEV(1);
        zona7.setFancoilSet(-1);
        zona7.setFancoil(-1);
        zona7.setZoneId(7);
        zona7.setCrono(arrayList);
        zona7.setSetUmd("560");
        zona7.setUmd("560");
        arrayList9.add(zona7);
        controlUnit.setZone(arrayList9);
        this.controlunit_list.add(controlUnit);
        ControlUnit controlUnit2 = new ControlUnit(context.getResources().getString(R.string.demo_controlunit3));
        controlUnit2.setSerial("414212345679");
        controlUnit2.setIcontype(0);
        controlUnit2.setUnitOfMesure(0);
        controlUnit2.setIsOff(true);
        controlUnit2.setOperatingMode(1);
        controlUnit2.setIsCooling(false);
        controlUnit2.setErrors(Functions.geterror(128));
        controlUnit2.setNumError(1);
        controlUnit2.setIr_present(0);
        Device device2 = new Device();
        device2.setLVDV_Type(Constants.DEVICE_TYPE_PROAIR);
        device2.setSerial(controlUnit2.getSerial());
        device2.setName(controlUnit2.getName());
        Plant plant2 = new Plant();
        plant2.setLVPL_Icon(controlUnit2.getIcontype());
        plant2.setLVPL_Name(controlUnit2.getName());
        plant2.setListDevices(new ArrayList());
        plant2.setLVPL_Id(2);
        plant2.getListDevices().add(device2);
        Constants.listaImpianti.add(plant2);
        ArrayList arrayList10 = new ArrayList();
        Zona zona8 = new Zona();
        zona8.setName(context.getResources().getString(R.string.demo_cu3_zone1));
        zona8.setOff(true);
        zona8.setManCrono(0);
        zona8.setTemp("18.0");
        zona8.setSetTemp("20");
        zona8.setSerrandaSet(-1);
        zona8.setSerranda(-1);
        zona8.setEV(0);
        zona8.setFancoilSet(-1);
        zona8.setFancoil(-1);
        zona8.setZoneId(1);
        zona8.setCrono(arrayList);
        zona8.setCWin(0);
        arrayList10.add(zona8);
        Zona zona9 = new Zona();
        zona9.setName(context.getResources().getString(R.string.demo_cu3_zone2));
        zona9.setOff(true);
        zona9.setManCrono(1);
        zona9.setTemp("17.5");
        zona9.setSetTemp("21");
        zona9.setSerrandaSet(-1);
        zona9.setSerranda(-1);
        zona9.setEV(0);
        zona9.setFancoilSet(-1);
        zona9.setFancoil(-1);
        zona9.setZoneId(2);
        zona9.setCrono(arrayList);
        zona9.setCWin(0);
        arrayList10.add(zona9);
        Zona zona10 = new Zona();
        zona10.setName(context.getResources().getString(R.string.demo_cu3_zone3));
        zona10.setOff(true);
        zona10.setManCrono(0);
        zona10.setTemp("16.0");
        zona10.setSetTemp("17");
        zona10.setSerrandaSet(-1);
        zona10.setSerranda(-1);
        zona10.setEV(0);
        zona10.setFancoilSet(-1);
        zona10.setFancoil(-1);
        zona10.setZoneId(3);
        zona10.setCrono(arrayList);
        zona10.setCWin(0);
        arrayList10.add(zona10);
        Zona zona11 = new Zona();
        zona11.setName(context.getResources().getString(R.string.demo_cu3_zone4));
        zona11.setOff(true);
        zona11.setManCrono(0);
        zona11.setTemp("16.5");
        zona11.setSetTemp("16");
        zona11.setSerrandaSet(-1);
        zona11.setSerranda(-1);
        zona11.setEV(0);
        zona11.setFancoilSet(-1);
        zona11.setFancoil(-1);
        zona11.setZoneId(4);
        zona11.setCrono(arrayList);
        zona11.setErrors(Functions.geterror(4));
        zona11.setNumError(1);
        zona11.setCWin(0);
        arrayList10.add(zona11);
        Zona zona12 = new Zona();
        zona12.setName(context.getResources().getString(R.string.demo_cu3_zone5));
        zona12.setOff(true);
        zona12.setManCrono(1);
        zona12.setTemp("16.5");
        zona12.setSetTemp("16");
        zona12.setSerrandaSet(-1);
        zona12.setSerranda(-1);
        zona12.setEV(0);
        zona12.setFancoilSet(-1);
        zona12.setFancoil(-1);
        zona12.setZoneId(4);
        zona12.setCrono(arrayList);
        zona12.setCWin(0);
        arrayList10.add(zona12);
        Zona zona13 = new Zona();
        zona13.setName(context.getResources().getString(R.string.demo_cu3_zone6));
        zona13.setOff(true);
        zona13.setManCrono(1);
        zona13.setTemp("16.0");
        zona13.setSetTemp("16");
        zona13.setSerrandaSet(-1);
        zona13.setSerranda(-1);
        zona13.setEV(0);
        zona13.setFancoilSet(-1);
        zona13.setFancoil(-1);
        zona13.setZoneId(4);
        zona13.setCrono(arrayList);
        zona13.setCWin(0);
        arrayList10.add(zona13);
        controlUnit2.setZone(arrayList10);
        this.controlunit_list.add(controlUnit2);
        ControlUnit controlUnit3 = new ControlUnit(context.getResources().getString(R.string.demo_controlunit2));
        controlUnit3.setSerial("414212345676");
        controlUnit3.setUnitOfMesure(0);
        controlUnit3.setIsOff(false);
        controlUnit3.setIcontype(2);
        controlUnit3.setOperatingMode(1);
        controlUnit3.setIsCooling(false);
        controlUnit3.setIr_present(0);
        Pico pico = new Pico();
        pico.setName(context.getResources().getString(R.string.demo_pico2));
        pico.setSerial("414312345678");
        pico.setOff(false);
        pico.setPCOM_Id(4L);
        pico.setHumvel(1);
        pico.setVentvel(1);
        pico.setHas_slave(1);
        pico.setPicoSlave(new ArrayList());
        Pico.Slave slave = new Pico.Slave();
        slave.setName(context.getResources().getString(R.string.mc_slaveDemo1));
        slave.setVerso(Pico.Slave.VERSOSYNC);
        slave.setMode(3);
        slave.setId_slave(1);
        slave.setSet_stato(1);
        pico.getPicoSlave().add(slave);
        pico.getPicoSlave().add((Object) null);
        Pico.Slave slave2 = new Pico.Slave();
        slave2.setName(context.getResources().getString(R.string.mc_slaveDemo2));
        slave2.setVerso(Pico.Slave.VERSOASYNC);
        slave2.setMode(3);
        slave2.setId_slave(3);
        slave2.setSet_stato(1);
        pico.getPicoSlave().add(slave2);
        Pico.Slave slave3 = new Pico.Slave();
        slave3.setName(context.getResources().getString(R.string.mc_slaveDemo3));
        slave3.setVerso(Pico.Slave.VERSOSYNC);
        slave3.setMode(3);
        slave3.setId_slave(4);
        slave3.setSet_stato(1);
        pico.getPicoSlave().add(slave3);
        this.pico_list.add(pico);
        Device device3 = new Device();
        device3.setLVDV_Type(Constants.DEVICE_TYPE_PROAIR);
        device3.setSerial(controlUnit3.getSerial());
        device3.setName(controlUnit3.getName());
        Plant plant3 = new Plant();
        plant3.setLVPL_Icon(controlUnit3.getIcontype());
        plant3.setLVPL_Name(controlUnit3.getName());
        plant3.setListDevices(new ArrayList());
        plant3.setLVPL_Id(3);
        plant3.getListDevices().add(device3);
        Device device4 = new Device();
        device4.setLVDV_Type(Constants.DEVICE_TYPE_PICO);
        device4.setSerial(pico.getSerial());
        device4.setName(pico.getName());
        plant3.getListDevices().add(device4);
        Constants.listaImpianti.add(plant3);
        ArrayList arrayList11 = new ArrayList();
        Zona zona14 = new Zona();
        zona14.setName(context.getResources().getString(R.string.demo_cu2_zone1));
        zona14.setOff(false);
        zona14.setManCrono(0);
        zona14.setTemp("25.0");
        zona14.setSetTemp("25");
        zona14.setSerrandaSet(7);
        zona14.setSerranda(0);
        zona14.setEV(-1);
        zona14.setFancoilSet(7);
        zona14.setFancoil(0);
        zona14.setZoneId(1);
        zona14.setCrono(arrayList);
        arrayList11.add(zona14);
        Zona zona15 = new Zona();
        zona15.setName(context.getResources().getString(R.string.demo_cu2_zone2));
        zona15.setOff(false);
        zona15.setManCrono(1);
        zona15.setTemp("23.5");
        zona15.setSetTemp("24");
        zona15.setSerrandaSet(2);
        zona15.setSerranda(2);
        zona15.setEV(-1);
        zona15.setFancoilSet(2);
        zona15.setFancoil(2);
        zona15.setZoneId(2);
        zona15.setCrono(arrayList);
        arrayList11.add(zona15);
        Zona zona16 = new Zona();
        zona16.setName(context.getResources().getString(R.string.demo_cu2_zone3));
        zona16.setOff(false);
        zona16.setManCrono(0);
        zona16.setTemp("23.0");
        zona16.setSetTemp("25");
        zona16.setSerrandaSet(3);
        zona16.setSerranda(3);
        zona16.setEV(-1);
        zona16.setFancoilSet(3);
        zona16.setFancoil(3);
        zona16.setZoneId(3);
        zona16.setCrono(arrayList);
        arrayList11.add(zona16);
        Zona zona17 = new Zona();
        zona17.setName(context.getResources().getString(R.string.demo_cu2_zone4));
        zona17.setOff(false);
        zona17.setManCrono(0);
        zona17.setTemp("24.5");
        zona17.setSetTemp("25");
        zona17.setSerrandaSet(1);
        zona17.setSerranda(1);
        zona17.setEV(-1);
        zona17.setFancoilSet(1);
        zona17.setFancoil(1);
        zona17.setZoneId(4);
        zona17.setCrono(arrayList);
        arrayList11.add(zona17);
        controlUnit3.setZone(arrayList11);
        this.controlunit_list.add(controlUnit3);
        ControlUnit controlUnit4 = new ControlUnit(context.getResources().getString(R.string.demo_controlunit4));
        controlUnit4.setSerial("414212345677");
        controlUnit4.setUnitOfMesure(0);
        controlUnit4.setIsOff(false);
        controlUnit4.setIcontype(3);
        controlUnit4.setOperatingMode(1);
        controlUnit4.setIsCooling(false);
        controlUnit4.setIr_present(0);
        ArrayList arrayList12 = new ArrayList();
        Device device5 = new Device();
        device5.setLVDV_Type(Constants.DEVICE_TYPE_PROAIR);
        device5.setSerial(controlUnit4.getSerial());
        device5.setName(controlUnit4.getName());
        Plant plant4 = new Plant();
        plant4.setLVPL_Icon(controlUnit4.getIcontype());
        plant4.setLVPL_Name(controlUnit4.getName());
        plant4.setListDevices(new ArrayList());
        plant4.setLVPL_Id(4);
        plant4.getListDevices().add(device5);
        Constants.listaImpianti.add(plant4);
        Zona zona18 = new Zona();
        zona18.setName(context.getResources().getString(R.string.demo_cu4_zone1));
        zona18.setOff(false);
        zona18.setManCrono(0);
        zona18.setTemp("24.0");
        zona18.setSetTemp("25");
        zona18.setSerrandaSet(1);
        zona18.setSerranda(1);
        zona18.setEV(-1);
        zona18.setFancoilSet(-1);
        zona18.setFancoil(-1);
        zona18.setZoneId(1);
        zona18.setCrono(arrayList);
        arrayList12.add(zona18);
        Zona zona19 = new Zona();
        zona19.setName(context.getResources().getString(R.string.demo_cu4_zone2));
        zona19.setOff(false);
        zona19.setManCrono(0);
        zona19.setTemp("24.5");
        zona19.setSetTemp("25");
        zona19.setSerrandaSet(1);
        zona19.setSerranda(1);
        zona19.setEV(-1);
        zona19.setFancoilSet(-1);
        zona19.setFancoil(-1);
        zona19.setZoneId(2);
        zona19.setCrono(arrayList);
        arrayList12.add(zona19);
        Zona zona20 = new Zona();
        zona20.setName(context.getResources().getString(R.string.demo_cu4_zone3));
        zona20.setOff(false);
        zona20.setManCrono(0);
        zona20.setTemp("22.0");
        zona20.setSetTemp("22");
        zona20.setSerrandaSet(-1);
        zona20.setSerranda(-1);
        zona20.setEV(-1);
        zona20.setFancoilSet(-1);
        zona20.setFancoil(-1);
        zona20.setZoneId(3);
        zona20.setCrono(arrayList);
        zona20.setCBadge(Double.valueOf(1.0d));
        zona20.setCoff(false);
        arrayList12.add(zona20);
        Zona zona21 = new Zona();
        zona21.setName(context.getResources().getString(R.string.demo_cu4_zone4));
        zona21.setOff(false);
        zona21.setManCrono(0);
        zona21.setTemp("23.5");
        zona21.setSetTemp("23");
        zona21.setSerrandaSet(7);
        zona21.setSerranda(0);
        zona21.setEV(-1);
        zona21.setFancoilSet(-1);
        zona21.setFancoil(-1);
        zona21.setZoneId(4);
        zona21.setCrono(arrayList);
        zona21.setCBadge((Object) null);
        arrayList12.add(zona21);
        Zona zona22 = new Zona();
        zona22.setName(context.getResources().getString(R.string.demo_cu4_zone5));
        zona22.setOff(false);
        zona22.setManCrono(0);
        zona22.setTemp("21.5");
        zona22.setSetTemp("22");
        zona22.setSerrandaSet(-1);
        zona22.setSerranda(-1);
        zona22.setEV(-1);
        zona22.setFancoilSet(-1);
        zona22.setFancoil(-1);
        zona22.setCBadge((Object) null);
        zona22.setCWin((Object) null);
        zona22.setZoneId(5);
        zona22.setCrono(arrayList);
        arrayList12.add(zona22);
        Zona zona23 = new Zona();
        zona23.setName(context.getResources().getString(R.string.demo_cu4_zone6));
        zona23.setOff(false);
        zona23.setManCrono(0);
        zona23.setTemp("19.0");
        zona23.setSetTemp("20");
        zona23.setSerrandaSet(2);
        zona23.setSerranda(2);
        zona23.setEV(-1);
        zona23.setFancoilSet(-1);
        zona23.setFancoil(-1);
        zona23.setZoneId(6);
        zona23.setCBadge(1);
        zona23.setCrono(arrayList);
        arrayList12.add(zona23);
        Zona zona24 = new Zona();
        zona24.setName(context.getResources().getString(R.string.demo_cu4_zone7));
        zona24.setOff(false);
        zona24.setManCrono(0);
        zona24.setTemp("21.5");
        zona24.setSetTemp("22");
        zona24.setSerrandaSet(3);
        zona24.setSerranda(3);
        zona24.setEV(-1);
        zona24.setFancoilSet(-1);
        zona24.setFancoil(-1);
        zona24.setZoneId(7);
        zona24.setCBadge(1);
        zona24.setCWin(1);
        zona24.setCrono(arrayList);
        arrayList12.add(zona24);
        Zona zona25 = new Zona();
        zona25.setName(context.getResources().getString(R.string.demo_cu4_zone8));
        zona25.setOff(true);
        zona25.setManCrono(0);
        zona25.setTemp("21.0");
        zona25.setSetTemp("22");
        zona25.setSerrandaSet(-1);
        zona25.setSerranda(-1);
        zona25.setEV(-1);
        zona25.setFancoilSet(-1);
        zona25.setFancoil(-1);
        zona25.setZoneId(8);
        zona25.setCBadge((Object) null);
        zona25.setCrono(arrayList);
        arrayList12.add(zona25);
        Zona zona26 = new Zona();
        zona26.setName(context.getResources().getString(R.string.demo_cu4_zone9));
        zona26.setOff(false);
        zona26.setManCrono(0);
        zona26.setTemp("20.5");
        zona26.setSetTemp("23");
        zona26.setSerrandaSet(3);
        zona26.setSerranda(3);
        zona26.setEV(-1);
        zona26.setFancoilSet(-1);
        zona26.setFancoil(-1);
        zona26.setZoneId(9);
        zona26.setCBadge(1);
        zona26.setCrono(arrayList);
        arrayList12.add(zona26);
        Zona zona27 = new Zona();
        zona27.setName(context.getResources().getString(R.string.demo_cu4_zone10));
        zona27.setOff(true);
        zona27.setManCrono(0);
        zona27.setTemp("21.5");
        zona27.setSetTemp("22");
        zona27.setSerrandaSet(-1);
        zona27.setSerranda(-1);
        zona27.setEV(-1);
        zona27.setFancoilSet(-1);
        zona27.setFancoil(-1);
        zona27.setZoneId(10);
        zona27.setCBadge(1);
        zona27.setCrono(arrayList);
        arrayList12.add(zona27);
        controlUnit4.setZone(arrayList12);
        this.controlunit_list.add(controlUnit4);
        ControlUnit controlUnit5 = new ControlUnit(context.getResources().getString(R.string.demo_controlunit5));
        controlUnit5.setSerial("414212345675");
        controlUnit5.setUnitOfMesure(0);
        controlUnit5.setIsOff(false);
        controlUnit5.setIcontype(1);
        controlUnit5.setOperatingMode(1);
        controlUnit5.setIsCooling(false);
        controlUnit5.setIr_present(0);
        ArrayList arrayList13 = new ArrayList();
        Device device6 = new Device();
        device6.setLVDV_Type(Constants.DEVICE_TYPE_PROAIR);
        device6.setSerial(controlUnit5.getSerial());
        device6.setName(controlUnit5.getName());
        Plant plant5 = new Plant();
        plant5.setLVPL_Icon(controlUnit5.getIcontype());
        plant5.setLVPL_Name(controlUnit5.getName());
        plant5.setListDevices(new ArrayList());
        String str = "21.5";
        plant5.setLVPL_Id(5);
        plant5.getListDevices().add(device6);
        Constants.listaImpianti.add(plant5);
        Zona zona28 = new Zona();
        zona28.setName(context.getResources().getString(R.string.demo_cu5_zone1));
        zona28.setOff(false);
        zona28.setManCrono(0);
        zona28.setTemp("24.0");
        zona28.setSetTemp("25");
        zona28.setSerrandaSet(1);
        zona28.setSerranda(1);
        zona28.setEV(-1);
        zona28.setFancoilSet(-1);
        zona28.setFancoil(-1);
        zona28.setZoneId(1);
        zona28.setCrono(arrayList);
        arrayList13.add(zona28);
        Zona zona29 = new Zona();
        zona29.setName(context.getResources().getString(R.string.demo_cu5_zone2));
        zona29.setOff(false);
        zona29.setManCrono(0);
        zona29.setTemp("24.5");
        zona29.setSetTemp("25");
        zona29.setSerrandaSet(1);
        zona29.setSerranda(1);
        zona29.setEV(-1);
        zona29.setFancoilSet(-1);
        zona29.setFancoil(-1);
        zona29.setZoneId(2);
        zona29.setCrono(arrayList);
        arrayList13.add(zona29);
        Zona zona30 = new Zona();
        zona30.setName(context.getResources().getString(R.string.demo_cu5_zone3));
        zona30.setOff(true);
        zona30.setManCrono(0);
        zona30.setTemp("22.0");
        zona30.setSetTemp("22");
        zona30.setSerrandaSet(-1);
        zona30.setSerranda(-1);
        zona30.setEV(-1);
        zona30.setFancoilSet(-1);
        zona30.setFancoil(-1);
        zona30.setZoneId(3);
        zona30.setCrono(arrayList);
        arrayList13.add(zona30);
        Zona zona31 = new Zona();
        zona31.setName(context.getResources().getString(R.string.demo_cu5_zone4));
        zona31.setOff(false);
        zona31.setManCrono(0);
        zona31.setTemp("23.5");
        zona31.setSetTemp("23");
        zona31.setSerrandaSet(7);
        zona31.setSerranda(0);
        zona31.setEV(-1);
        zona31.setFancoilSet(-1);
        zona31.setFancoil(-1);
        zona31.setZoneId(4);
        zona31.setCrono(arrayList);
        arrayList13.add(zona31);
        Zona zona32 = new Zona();
        zona32.setName(context.getResources().getString(R.string.demo_cu5_zone5));
        zona32.setOff(true);
        zona32.setManCrono(0);
        zona32.setTemp(str);
        zona32.setSetTemp("22");
        zona32.setSerrandaSet(-1);
        zona32.setSerranda(-1);
        zona32.setEV(-1);
        zona32.setFancoilSet(-1);
        zona32.setFancoil(-1);
        zona32.setZoneId(5);
        zona32.setCrono(arrayList);
        arrayList13.add(zona32);
        Zona zona33 = new Zona();
        zona33.setName(context.getResources().getString(R.string.demo_cu5_zone6));
        zona33.setOff(false);
        zona33.setManCrono(0);
        zona33.setTemp("19.0");
        zona33.setSetTemp("20");
        zona33.setSerrandaSet(2);
        zona33.setSerranda(2);
        zona33.setEV(-1);
        zona33.setFancoilSet(-1);
        zona33.setFancoil(-1);
        zona33.setZoneId(6);
        zona33.setCrono(arrayList);
        arrayList13.add(zona33);
        Zona zona34 = new Zona();
        zona34.setName(context.getResources().getString(R.string.demo_cu5_zone7));
        zona34.setOff(false);
        zona34.setManCrono(0);
        zona34.setTemp(str);
        zona34.setSetTemp("22");
        zona34.setSerrandaSet(3);
        zona34.setSerranda(3);
        zona34.setEV(-1);
        zona34.setFancoilSet(-1);
        zona34.setFancoil(-1);
        zona34.setZoneId(7);
        zona34.setCrono(arrayList);
        arrayList13.add(zona34);
        Zona zona35 = new Zona();
        zona35.setName(context.getResources().getString(R.string.demo_cu5_zone8));
        zona35.setOff(true);
        zona35.setManCrono(0);
        zona35.setTemp("21.0");
        zona35.setSetTemp("22");
        zona35.setSerrandaSet(-1);
        zona35.setSerranda(-1);
        zona35.setEV(-1);
        zona35.setFancoilSet(-1);
        zona35.setFancoil(-1);
        zona35.setZoneId(8);
        zona35.setCrono(arrayList);
        arrayList13.add(zona35);
        controlUnit5.setZone(arrayList13);
        this.controlunit_list.add(controlUnit5);
        Collections.sort(Constants.listaImpianti, new CustomComparatorPlant());
    }

    private static class CustomComparatorPlant implements Comparator<Plant> {
        private CustomComparatorPlant() {
        }

        public int compare(Plant plant, Plant plant2) {
            return plant.getLVPL_Name().compareTo(plant2.getLVPL_Name());
        }
    }

    private static class CustomComparatorDev implements Comparator<Device> {
        private CustomComparatorDev() {
        }

        public int compare(Device device, Device device2) {
            return device.getName().compareTo(device2.getName());
        }
    }

    private Zona create_zone(String str, boolean z, boolean z2, int i, String str2, String str3, int i2, int i3, int i4, int i5, List<List<Crono>> list) {
        Zona zona = new Zona();
        zona.setName(str);
        zona.setOff(z);
        zona.setFasciaAttiva(!z2);
        zona.setManCrono(i);
        zona.setTemp(str3);
        zona.setSetTemp(str2);
        zona.setSerrandaSet(i2);
        zona.setFancoilSet(i4);
        zona.setZoneId(i5);
        zona.setCrono(list);
        return zona;
    }
}
